In [1]:
import pandas as pd
import numpy as np

In [42]:
df = pd .read_csv("C:/Users/sagar/Downloads/data_analyst_task_1_submission/raw_customer_data.csv.csv")

In [43]:
df

,Customer ID,Customer Name,Gender,Country,Join Date,Age,Email,Annual Income
0,101,John Smith,Male,India,01/02/2025,28.0,john@example.com,45000
1,102,Priya Sharma,female,india,2025-02-03,31.0,priya@example.com,52000
2,103,Rahul Kumar,M,INDIA,03-02-2025,27.0,rahul@example.com,48000
3,104,Anita Rao,F,India,04/02/2025,NaN,anita@example.com,61000
4,105,Vikram Singh,Male,India,2025/02/05,35.0,NaN,57000
5,106,Sneha Patel,Female,INDIA,06-02-2025,29.0,sneha@example.com,49500
6,107,Arjun Mehta,m,india,07/02/25,33.0,arjun@example.com,68000
7,108,Kavya Nair,FEMALE,India,2025-02-08,26.0,kavya@example.com,51000
8,109,Rohan Das,Male,INDIA,09/02/2025,30.0,rohan@example.com,55000
9,110,Meera Iyer,female,india,10-02-2025,32.0,meera@example.com,62500
10,111,John Smith,Male,India,01/02/2025,28.0,john@example.com,45000
11,112,Suresh Babu,M,India,12/02/2025,41.0,suresh@example.com,72000
12,113,Lakshmi Devi,Female,india,13/02/2025,38.0,lakshmi@example.com,64000
13,114,Amit Shah,male,INDIA,14/02/2025,34.0,amit@example.com,59000
14,115,Pooja Verma,F,India,15/02/2025,25.0,pooja@example.com,47000
15,116,Naveen Kumar,Male,India,16/02/2025,NaN,naveen@example.com,53000
16,117,Divya Reddy,female,INDIA,17/02/2025,29.0,divya@example.com,50500
17,118,Manoj Hegde,M,india,18/02/2025,37.0,manoj@example.com,69000
18,119,Swati Joshi,Female,India,19/02/2025,28.0,swati@example.com,51500
19,120,Kiran Rao,m,INDIA,20/02/2025,36.0,kiran@example.com,60000

In [44]:
df.head()

,Customer ID,Customer Name,Gender,Country,Join Date,Age,Email,Annual Income
0,101,John Smith,Male,India,01/02/2025,28.0,john@example.com,45000
1,102,Priya Sharma,female,india,2025-02-03,31.0,priya@example.com,52000
2,103,Rahul Kumar,M,INDIA,03-02-2025,27.0,rahul@example.com,48000
3,104,Anita Rao,F,India,04/02/2025,NaN,anita@example.com,61000
4,105,Vikram Singh,Male,India,2025/02/05,35.0,NaN,57000

In [45]:
df.shape

(20, 8)

In [46]:
df.columns

Index(['Customer ID', 'Customer Name', 'Gender', 'Country', 'Join Date', 'Age',
       'Email', 'Annual Income'],
      dtype='object')

In [47]:
df.isnull().sum()

Customer ID      0
Customer Name    0
Gender           0
Country          0
Join Date        0
Age              2
Email            1
Annual Income    0
dtype: int64

In [48]:
df.duplicated().sum()

np.int64(0)

In [49]:
df[df.duplicated()]

Empty DataFrame
Columns: [Customer ID, Customer Name, Gender, Country, Join Date, Age, Email, Annual Income]
Index: []

In [50]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Customer ID    20 non-null     int64
 1   Customer Name  20 non-null     object
 2   Gender         20 non-null     object
 3   Country        20 non-null     object
 4   Join Date      20 non-null     object
 5   Age            18 non-null     float64
 6   Email          19 non-null     object
 7   Annual Income  20 non-null     int64
dtypes: float64(1), int64(2), object(5)
memory usage: 1.4+ KB

In [51]:
df.columns = (
    df.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
)

In [52]:
df.columns

Index(['customer_id', 'customer_name', 'gender', 'country', 'join_date', 'age',
       'email', 'annual_income'],
      dtype='object')

In [53]:
for col in ["customer_name", "gender", "country", "email"]:
    df[col] = df[col].apply(
        lambda x: x.strip() if isinstance(x, str) else x
    )

In [54]:
gender_map = {
    "m": "Male",
    "male": "Male",
    "f": "Female",
    "female": "Female"
}

df["gender"] = df["gender"].str.lower().map(gender_map)

In [55]:
df["gender"].value_counts()

gender
Male      11
Female     9
Name: count, dtype: int64

In [56]:
df["country"] = df["country"].str.title()

In [57]:
df["country"].value_counts()

country
India    20
Name: count, dtype: int64

In [58]:
df["join_date"] = pd.to_datetime(
    df["join_date"],
    dayfirst=True,
    errors="coerce"
)

In [59]:
df["join_date"].head()

0   2025-02-01
1          NaT
2          NaT
3   2025-02-04
4          NaT
Name: join_date, dtype: datetime64[ns]

In [60]:
df["join_date"] = df["join_date"].dt.strftime("%d-%m-%Y")

In [61]:
df["age"] = pd.to_numeric(df["age"], errors="coerce")

In [62]:
df["age"].dtype

dtype('float64')

In [63]:
df["age"].median()

30.5

In [64]:
df["age"] = df["age"].fillna(df["age"].median())

In [65]:
df["age"].isnull().sum()

np.int64(0)

In [66]:
df["email"] = df["email"].fillna("Not Provided")

In [67]:
df["email"].isnull().sum()

np.int64(0)

In [68]:
df["annual_income"] = pd.to_numeric(
    df["annual_income"],
    errors="coerce"
)

In [69]:
duplicate_columns = [
    "customer_name",
    "gender",
    "country",
    "join_date",
    "age",
    "email",
    "annual_income"
]

df = df.drop_duplicates(
    subset=duplicate_columns,
    keep="first"
).reset_index(drop=True)

In [70]:
df.duplicated().sum()

np.int64(0)

In [71]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19 entries, 0 to 18
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   customer_id    19 non-null     int64
 1   customer_name  19 non-null     object
 2   gender         19 non-null     object
 3   country        19 non-null     object
 4   join_date      12 non-null     object
 5   age            19 non-null     float64
 6   email          19 non-null     object
 7   annual_income  19 non-null     int64
dtypes: float64(1), int64(2), object(5)
memory usage: 1.3+ KB

In [72]:
df.isnull().sum()

customer_id      0
customer_name    0
gender           0
country          0
join_date        7
age              0
email            0
annual_income    0
dtype: int64

In [73]:
df.head(10)

,customer_id,customer_name,gender,country,join_date,age,email,annual_income
0,101,John Smith,Male,India,01-02-2025,28.0,john@example.com,45000
1,102,Priya Sharma,Female,India,NaN,31.0,priya@example.com,52000
2,103,Rahul Kumar,Male,India,NaN,27.0,rahul@example.com,48000
3,104,Anita Rao,Female,India,04-02-2025,30.5,anita@example.com,61000
4,105,Vikram Singh,Male,India,NaN,35.0,Not Provided,57000
5,106,Sneha Patel,Female,India,NaN,29.0,sneha@example.com,49500
6,107,Arjun Mehta,Male,India,NaN,33.0,arjun@example.com,68000
7,108,Kavya Nair,Female,India,NaN,26.0,kavya@example.com,51000
8,109,Rohan Das,Male,India,09-02-2025,30.0,rohan@example.com,55000
9,110,Meera Iyer,Female,India,NaN,32.0,meera@example.com,62500

In [74]:
df.shape

(19, 8)

In [75]:
df.to_csv(
    "cleaned_customer_data.csv",
    index=False
)

In [76]:
summary = {
    "Initial rows": 20,
    "Final rows": len(df),
    "Duplicate records removed": 1,
    "Missing age values filled": 2,
    "Missing email values filled": 1,
    "Gender standardized": "Yes",
    "Country standardized": "Yes",
    "Date format standardized": "Yes",
    "Column names standardized": "Yes",
    "Data types corrected": "Yes"
}

summary_df = pd.DataFrame(
    list(summary.items()),
    columns=["Cleaning Operation", "Result"]
)

summary_df

            Cleaning Operation Result
0                 Initial rows     20
1                   Final rows     19
2    Duplicate records removed      1
3    Missing age values filled      2
4  Missing email values filled      1
5          Gender standardized    Yes
6         Country standardized    Yes
7     Date format standardized    Yes
8    Column names standardized    Yes
9         Data types corrected    Yes

In [77]:
summary_df.to_csv(
    "C:/Users/sagar/Downloads/data_analyst_task_1_submission/cleaned_customer_data.csv.csv",
    index=False
)

In [81]:
df = pd .read_csv("C:/Users/sagar/Downloads/data_analyst_task_1_submission/raw_customer_data.csv.csv")
df.head(10)

,Customer ID,Customer Name,Gender,Country,Join Date,Age,Email,Annual Income
0,101,John Smith,Male,India,01/02/2025,28.0,john@example.com,45000
1,102,Priya Sharma,female,india,2025-02-03,31.0,priya@example.com,52000
2,103,Rahul Kumar,M,INDIA,03-02-2025,27.0,rahul@example.com,48000
3,104,Anita Rao,F,India,04/02/2025,NaN,anita@example.com,61000
4,105,Vikram Singh,Male,India,2025/02/05,35.0,NaN,57000
5,106,Sneha Patel,Female,INDIA,06-02-2025,29.0,sneha@example.com,49500
6,107,Arjun Mehta,m,india,07/02/25,33.0,arjun@example.com,68000
7,108,Kavya Nair,FEMALE,India,2025-02-08,26.0,kavya@example.com,51000
8,109,Rohan Das,Male,INDIA,09/02/2025,30.0,rohan@example.com,55000
9,110,Meera Iyer,female,india,10-02-2025,32.0,meera@example.com,62500

In [82]:
df.isnull().sum()

Customer ID      0
Customer Name    0
Gender           0
Country          0
Join Date        0
Age              2
Email            1
Annual Income    0
dtype: int64

In [83]:
df.duplicated().sum()

np.int64(0)

In [84]:
df.duplicated().sum()

np.int64(0)